In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,7],[5,12,8]],columns=['cgpa','resume_score','package'])

In [4]:
df

   cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        7
3     5            12        8

In [5]:
np.random.seed(3)
print(np.random.randint(1, 10, 5))

[9 4 9 9 1]

In [6]:
print(np.random.randint(1, 10, 5))

[6 4 6 8 7]

In [7]:
def param_init(layers_dense):
  np.random.seed(3)
  parameter={};
  L = len(layers_dense)
  for i in range(1,L):
    parameter['w'+str(i)]=np.ones((layers_dense[i-1],layers_dense[i]))*0.1
    parameter['b'+str(i)]=np.zeros((layers_dense[i],1))

  return parameter

In [8]:
param_init([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [9]:
def linear_forward(x,w,b):
  z = np.dot(w.T,x)+b

  return z

In [41]:
#main fUnction foe forward Prpogation
def L_layer_forward(X,parameter):
  A = X
  L = len(parameter)//2 # No. of layers in neural network
  for i in range(1,L+1):
    A_prev = A
    w1 = parameter['w'+str(i)]
    b1 = parameter['b'+str(i)]
    # print('A'+str(i-1)+': ',A_prev)
    # print('w'+str(i)+': ',w1)
    # print('b'+str(i)+': ',b1)
    # print('---'*15)

    A = linear_forward(A_prev,w1,b1)
    # print('A'+str(i)+': ',A)
    # print('***'*15)

  return A,A_prev

In [11]:
X= df[['cgpa','resume_score']].values[0].reshape(2,1)
y = df[['package']].values[0][0]
parameter = param_init([2,2,1])

In [12]:
parameter

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [13]:
y_hat,A1 = L_layer_forward(X,parameter)

A0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
---------------------------------------------
A1:  [[1.6]
 [1.6]]
*********************************************
A1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
---------------------------------------------
A2:  [[0.32]]
*********************************************

In [14]:
# y_hat = y_hat[0][0]
y_hat

array([[0.32]])

In [15]:
A1

array([[1.6],
       [1.6]])

In [16]:
loss = (y-0.32)**2
print(loss)

13.5424

In [25]:
# student 2
X= df[['cgpa','resume_score']].values[1].reshape(2,1)
y = df[['package']].values[1][0]
y_hat2,A2 = L_layer_forward(X,parameter)

A0:  [[7]
 [9]]
w1:  [[0.10727474 0.10727474]
 [0.10796811 0.10796811]]
b1:  [[0.00090934]
 [0.00099601]]
---------------------------------------------
A1:  [[1.72354555]
 [1.72363222]]
*********************************************
A1:  [[1.72354555]
 [1.72363222]]
w2:  [[0.123552]
 [0.135328]]
b2:  [[0.142688]]
---------------------------------------------
A2:  [[0.5888912]]
*********************************************

In [31]:
# y_hat2=y_hat2[0][0]
y_hat2

np.float64(0.5888912007351502)

In [34]:
update_parameters(parameter,y,y_hat2,A2,X)

In [35]:
parameter

{'w1': array([[0.12584499, 0.13115077],
        [0.1280372 , 0.13377123]]),
 'b1': array([[0.00356224],
        [0.00386303]]),
 'w2': array([[0.15373349],
        [0.16551026]]),
 'b2': array([[0.17433248]])}

In [19]:
# def update_param(parameter,y,y_hat,A1,X):
#   parameter['w2'][0][0] = parameter['w2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
#   parameter['w2'][1][0] = parameter['w2'][0][0] + (0.001*2*(y-y_hat)*A1[1][0])
#   parameter['b2'][0][0] = parameter['b2'][0][0] + (0.001*2(y-y_hat))

#   parameter['w1'][1][0] = parameter['w1'][1][0] + (0.001*2(y-y_hat)*parameter['w2'][0][0]*X[1][0])
#   parameter['w1'][0][0] = parameter['w1'][0][0] + (0.001*2(y-y_hat)*parameter['w2'][0][0]*X[0][0])
#   parameter['b1'][0][0] = parameter['b1'][0][0] + (0.001*2(y-y_hat)*parameter['w2'][0][0])

#   parameter['w1'][0][1] = parameter['w1'][0][1] + (0.001*2(y-y_hat)*parameter['w2'][1][0]*X[0][0])
#   parameter['w1'][1][1] = parameter['w1'][1][1] + (0.001*2(y-y_hat)*parameter['w2'][1][0]*X[1][0])
#   parameter['b1'][1][0] = parameter['b1'][0][1] + (0.001*2(y-y_hat)*parameter['w2'][1][0])

In [20]:
# update_param(parameter,y,y_hat,A1,X)

In [32]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[0][0])
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0])

  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[0][0])
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0])

In [22]:
update_parameters(parameter,y,y_hat,A1,X)

/tmp/ipython-input-177651305.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipython-input-177651305.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipython-input-177651305.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat))
/tmp/ipython-input-177651305.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[0][0])
/tmp/ipython-input-177651305.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[1][0])
/tmp/ipython-input-177651305.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0])
/tmp/ipython-input-177651305.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[0][0])
/tmp/ipython-input-177651305.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[1][0])
/tmp/ipython-input-177651305.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0])

In [23]:
parameter

{'w1': array([[0.10727474, 0.10727474],
        [0.10796811, 0.10796811]]),
 'b1': array([[0.00090934],
        [0.00099601]]),
 'w2': array([[0.123552],
        [0.135328]]),
 'b2': array([[0.142688]])}

In [24]:
parameter['b1'][1][0]

np.float64(0.00099601408)

In [44]:
#epochs implimentation
parameter = param_init([2,2,1])
epochs = 10
for i in range(epochs):
  loss = []

  for j in range(df.shape[0]):
    X= df[['cgpa','resume_score']].values[j].reshape(2,1)
    y = df[['package']].values[j][0]

    y_hat,A1 = L_layer_forward(X,parameter)
    y_hat = y_hat[0][0]

    update_parameters(parameter,y,y_hat,A1,X)

    loss.append((y-y_hat)**2)

  print(f'epochs:{i}  loss:{np.array(loss).mean()}')

parameter

epochs:0  loss:31.48758738676033
epochs:1  loss:22.489403790974677
epochs:2  loss:10.93991216628426
epochs:3  loss:3.875765192198326
epochs:4  loss:2.4898946978737335
epochs:5  loss:2.611067213098769
epochs:6  loss:2.732006550529535
epochs:7  loss:2.7752963467505536
epochs:8  loss:2.7891998984842816
epochs:9  loss:2.794442058245532

{'w1': array([[0.24882114, 0.46393506],
        [0.26095321, 0.5062623 ]]),
 'b1': array([[0.03076098],
        [0.03397177]]),
 'w2': array([[0.43546086],
        [0.52721255]]),
 'b2': array([[0.53051353]])}

In [38]:
df.shape[0]

4

### TensorFlow + Keras

In [45]:
df.head()

   cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        7
3     5            12        8

In [46]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [48]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [49]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.get_weights()

[array([[-0.8610226 ,  0.2915572 ],
        [-0.91439533,  0.51691854]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.2646893],
        [-1.1740837]], dtype=float32),
 array([0.], dtype=float32)]

In [63]:
new_weight = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([.0,.0],dtype=np.float32),
              np.array([[0.1],[0.1]],dtype=np.float32),np.array([.0],dtype=np.float32)]

In [64]:
new_weight

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [65]:
model.set_weights(new_weight)

In [66]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [68]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [76]:
X = df.drop(columns=['package']).values
y = df['package'].values

In [77]:
X

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

In [78]:
y

array([4, 5, 7, 8])

In [82]:
model.fit(X,y,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1133
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5491
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7906
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5832
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7843
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0947
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8825
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6716
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.1052
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5567
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4370
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4180
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6593
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8662
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3272
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.6195
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0463
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7363
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6443
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8509
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5841
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.4392
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.9700
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8935
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.9618
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.2006
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8668
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1525
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5172
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5655
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1408
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5622
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3945
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9761
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.2841
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1256
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5480
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3892
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5957
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3394
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3853
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5089
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9493
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5058
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5168
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.2166
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7965
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3478
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7188
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5289

In [83]:
model.get_weights()

[array([[0.35740885, 0.35740885],
        [0.4411309 , 0.4411309 ]], dtype=float32),
 array([0.3099864, 0.3099864], dtype=float32),
 array([[0.41753942],
        [0.41753942]], dtype=float32),
 array([0.22827224], dtype=float32)]